# This is a basic workflow to help you get started with Actions+Terraform+Azure

name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"

    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TENANT_ID}}

    steps:

      - uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Check Path
        run: pwd

      - name: Check Files
        run: ls

      - name: Terraform Init
        run: terraform -chdir=./terraform init

      - name: Terraform Format
        run: terraform -chdir=./terraform fmt -check

      - name: Terraform Plan
        run: terraform -chdir=./terraform plan
      
      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve -var-file="./terraform/env/henry/dev.tfvars" -var="administrator_login_password=${{secrets.ADMIN_PASS}}" -var="django_superuser_password=${{secrets.ADMIN_DJANGO_PASS}}"